### ISSUE TITLE
Add help text for excerpt and note

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#1001]
Just to explain a little what they do and where they're shown.

**Comment by Floppy** [comment]
I think excerpt would be better as a single line input instead of a textarea, too...

**Comment by Floppy** [comment]
@ksuquix I'm thinking a bit about this, and I wonder if "description", "summary", or "subtitle" better reflect what "excerpt" is actually for? Excerpt seems like something that would be extracted from the note, but that could just be in *my* brain, not in anyone else's. What do you think?

**Comment by ksuquix** [comment]
@Floppy  I can live with summary/subtitle.   I'm used to working in confluence, which calls it excerpt.  Description is probably too close to the notes field.

I made it textarea at first because I was sticking in <img> fields for logos, but the storage we talked about on chat would be better for that.
